import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, LockKeyhole, Network } from "lucide-react";
import { useAuth } from "../hooks/useAuth";
export function AuthForm({ mode }: { mode: "login" | "register" }) {
	const navigate = useNavigate(); const { login, register } = useAuth(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
	const submit = async (event: FormEvent) => { event.preventDefault(); if (!email.includes("@") || password.length < 8 || (mode === "register" && !/\d/.test(password))) { setError("Use a valid email and a password with 8+ characters" + (mode === "register" ? " and a number." : ".")); return; } try { await (mode === "login" ? login(email, password) : register(email, password)); navigate("/chat"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Request failed"); } };
	return <main className="grid min-h-screen overflow-hidden bg-ink text-slate-100 lg:grid-cols-[1fr_0.9fr]">
		<section className="relative hidden overflow-hidden bg-gradient-to-br from-[#18343a] via-[#102229] to-ink p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-28 -top-28 h-72 w-72 rounded-full border border-coral/20 bg-coral/10 blur-sm" /><div className="relative"><div className="mb-8 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-coral text-ink"><Network size={21} /></span><span className="font-display text-xl font-bold">Nexus</span></div><p className="max-w-lg font-display text-5xl font-semibold leading-[1.05] tracking-tight text-white">See the signal inside the noise.</p><p className="mt-6 max-w-md text-lg leading-8 text-slate-300">A private financial knowledge graph for faster research, clearer context, and better questions.</p></div><p className="relative text-sm text-slate-500">Research workspace · v1.0</p></section>
		<section className="flex items-center justify-center px-6 py-12 sm:px-10"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-coral text-ink"><Network size={21} /></span><span className="font-display text-xl font-bold">Nexus</span></div></div><div className="mb-8"><div className="mb-4 inline-flex rounded-lg border border-white/10 bg-white/5 p-2 text-coral"><LockKeyhole size={18} /></div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Secure workspace</p><h1 className="font-display text-3xl font-semibold tracking-tight text-white">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-slate-400">{mode === "login" ? "Continue your research from where you left off." : "Start building your private research context."}</p></div><form className="space-y-4" onSubmit={submit}><label className="block text-sm font-medium text-slate-300">Email<input aria-label="Email" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white outline-none transition placeholder:text-slate-600 focus:border-coral/70 focus:ring-2 focus:ring-coral/20" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" /></label><label className="block text-sm font-medium text-slate-300">Password<input aria-label="Password" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-white outline-none transition placeholder:text-slate-600 focus:border-coral/70 focus:ring-2 focus:ring-coral/20" type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Your password" /></label>{error && <div role="alert" className="rounded-xl border border-coral/30 bg-coral/10 px-4 py-3 text-sm text-coral">{error}</div>}<button className="flex w-full items-center justify-center gap-2 rounded-xl bg-coral px-4 py-3.5 font-semibold text-ink shadow-glow transition hover:-translate-y-0.5 hover:bg-[#ff9b72]" type="submit">{mode === "login" ? "Enter workspace" : "Create workspace"}<ArrowRight size={17} /></button></form><p className="mt-6 text-center text-sm text-slate-500">{mode === "login" ? "New to Nexus?" : "Already have an account?"} <Link className="font-semibold text-mist hover:text-coral" to={mode === "login" ? "/register" : "/login"}>{mode === "login" ? "Create an account" : "Sign in"}</Link></p></div></section>
	</main>;
}
